name: Empty Commit

on:
  schedule:
    - cron: "*/5 * * * *" # Runs at midnight every day, adjust as needed
  workflow_dispatch: # Allows manual triggering

jobs:
  empty-commit:
    runs-on: macos-latest

    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: empty # Base branch

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create empty commit
        run: |
          # Generate a new branch name with timestamp
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')

          # Get the current date for the commit message
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')

          # Create an empty commit with the current date in the message
          git commit --allow-empty -m "Empty commit: $CURRENT_DATE"

          # Push the commit to the repository
          git push -f
